-- -----------------------------
-- Business Problem
-- Advanced Analysis
-- -----------------------------


/*
1. Top Selling Products
Query the top 10 products by total sales value.
Challenge: Include product_name, total quantity sold, and total sales value.
*/
SELECT
    p.product_id,
    p.product_name,
    SUM(oi.quantity)                       AS total_quantity_sold,
    SUM(oi.quantity * oi.price_per_unit)   AS total_sales_value
FROM order_items oi
JOIN product p ON p.product_id = oi.product_id
GROUP BY p.product_id, p.product_name
ORDER BY total_sales_value DESC LIMIT 10;


/*
2. Revenue by Category
Calculate total revenue generated by each product category.
Challenge: Include the percentage contribution of each category to total revenue.
*/
SELECT
    c.category_id,
    c.category_name,
    SUM(oi.quantity * oi.price_per_unit) AS category_revenue,
    ROUND(
        SUM(oi.quantity * oi.price_per_unit) * 100.0
        / (SELECT SUM(quantity * price_per_unit) FROM order_items), 2
    ) AS pct_of_total_revenue
FROM order_items oi
JOIN product  p ON p.product_id  = oi.product_id
JOIN category c ON c.category_id = p.category_id
GROUP BY c.category_id, c.category_name
ORDER BY category_revenue DESC;
 
 /*
3. Average Order Value (AOV)
Compute the average order value for each customer.
Challenge: Include only customers with more than 5 orders.
*/
SELECT
    o.customer_id,
    CONCAT(cu.first_name, ' ', cu.last_name) AS customer_name,
    COUNT(DISTINCT o.order_id)               AS total_orders,
    ROUND(
        SUM(oi.quantity * oi.price_per_unit) / COUNT(DISTINCT o.order_id), 2
    ) AS avg_order_value
FROM orders o
JOIN customer    cu ON cu.customer_id = o.customer_id
JOIN order_items oi ON oi.order_id    = o.order_id
GROUP BY o.customer_id, cu.first_name, cu.last_name
HAVING COUNT(DISTINCT o.order_id) > 5
ORDER BY avg_order_value DESC;
 
 
 /*
4. Monthly Sales Trend
Query monthly total sales over the past year.
Challenge: Display the sales trend, grouping by month, return current_month sale, last month sale.
*/
-- Note: "past year" is calculated relative to the most recent order_date in
-- the data (rather than CURDATE()) since this is a historical dataset.
WITH monthly_sales AS (
    SELECT
        DATE_FORMAT(o.order_date, '%Y-%m')   AS sales_month,
        SUM(oi.quantity * oi.price_per_unit) AS total_sales
    FROM orders o
    JOIN order_items oi ON oi.order_id = o.order_id
    WHERE o.order_date >= (
        SELECT DATE_SUB(MAX(order_date), INTERVAL 1 YEAR) FROM orders
    )
    GROUP BY DATE_FORMAT(o.order_date, '%Y-%m')
)
SELECT
    sales_month,
    total_sales                                              AS current_month_sale,
    LAG(total_sales) OVER (ORDER BY sales_month)              AS last_month_sale
FROM monthly_sales
ORDER BY sales_month;
 
 
/*
5. Customers with No Purchases
Find customers who have registered but never placed an order.
Challenge: List customer details and the time since their registration.
*/
-- Note: the customer table has no registration/signup date column, so
-- "time since registration" cannot be computed as-is. Add a signup_date
-- column to `customer` if that metric is required. The query below
-- returns everything else the question asks for.
SELECT
    cu.customer_id,
    CONCAT(cu.first_name, ' ', cu.last_name) AS customer_name,
    cu.state
FROM customer cu
LEFT JOIN orders o ON o.customer_id = cu.customer_id
WHERE o.order_id IS NULL;
 
 
/*
6. Best-Selling Categories by State
Identify the best-selling product category for each state.
Challenge: Include the total sales for that category within each state.
*/
WITH state_category_sales AS (
    SELECT
        cu.state,
        cat.category_name,
        SUM(oi.quantity * oi.price_per_unit) AS category_sales,
        RANK() OVER (
            PARTITION BY cu.state
            ORDER BY SUM(oi.quantity * oi.price_per_unit) DESC
        ) AS rnk
    FROM orders o
    JOIN customer    cu  ON cu.customer_id  = o.customer_id
    JOIN order_items oi  ON oi.order_id     = o.order_id
    JOIN product     p   ON p.product_id    = oi.product_id
    JOIN category     cat ON cat.category_id = p.category_id
    GROUP BY cu.state, cat.category_name
)
SELECT state, category_name, category_sales
FROM state_category_sales
WHERE rnk = 1
ORDER BY state;
 
 
/*
7. Customer Lifetime Value (CLTV)
Calculate the total value of orders placed by each customer over their lifetime.
Challenge: Rank customers based on their CLTV.
*/
SELECT
    o.customer_id,
    CONCAT(cu.first_name, ' ', cu.last_name) AS customer_name,
    SUM(oi.quantity * oi.price_per_unit)      AS cltv,
    RANK() OVER (ORDER BY SUM(oi.quantity * oi.price_per_unit) DESC) AS cltv_rank
FROM orders o
JOIN customer    cu ON cu.customer_id = o.customer_id
JOIN order_items oi ON oi.order_id    = o.order_id
GROUP BY o.customer_id, cu.first_name, cu.last_name
ORDER BY cltv_rank;
 
 
/*
8. Inventory Stock Alerts
Query products with stock levels below a certain threshold (e.g., less than 10 units).
Challenge: Include last restock date and warehouse information.
*/
SELECT
    i.product_id,
    p.product_name,
    i.stock,
    i.warehouse_id,
    i.last_stock_date
FROM inventory i
JOIN product p ON p.product_id = i.product_id
WHERE i.stock < 10
ORDER BY i.stock ASC;
 
 
/*
9. Shipping Delays
Identify orders where the shipping date is later than 7 days after the order date.
Challenge: Include customer, order details, and delivery provider.
*/
SELECT
    o.order_id,
    CONCAT(cu.first_name, ' ', cu.last_name) AS customer_name,
    o.order_date,
    s.shipping_date,
    DATEDIFF(s.shipping_date, o.order_date)  AS days_to_ship,
    s.shipping_providers,
    s.delivery_status
FROM orders o
JOIN customer cu ON cu.customer_id = o.customer_id
JOIN shipping s  ON s.order_id     = o.order_id
WHERE DATEDIFF(s.shipping_date, o.order_date) > 7
ORDER BY days_to_ship DESC;
 
 
/*
10. Payment Success Rate
Calculate the percentage of successful payments across all orders.
Challenge: Include breakdowns by payment status (e.g., failed, pending).
*/
SELECT
    payment_status,
    COUNT(*) AS status_count,
    ROUND(COUNT(*) * 100.0 / (SELECT COUNT(*) FROM payments), 2) AS pct_of_all_payments
FROM payments
GROUP BY payment_status
ORDER BY status_count DESC;
 
-- Overall success rate (single number)
SELECT
    ROUND(
        SUM(CASE WHEN payment_status = 'Completed' THEN 1 ELSE 0 END) * 100.0
        / COUNT(*), 2
    ) AS overall_payment_success_rate_pct
FROM payments;
 
 
/*
11. Top Performing Sellers
Find the top 5 sellers based on total sales value.
Challenge: Include both successful and failed orders, and display their
percentage of successful orders.
*/
WITH seller_sales AS (
    SELECT
        o.seller_id,
        se.seller_name,
        COUNT(DISTINCT o.order_id)                                              AS total_orders,
        SUM(CASE WHEN o.order_status = 'Completed' THEN 1 ELSE 0 END)           AS successful_orders,
        SUM(CASE WHEN o.order_status IN ('Cancelled','Returned') THEN 1 ELSE 0 END) AS failed_orders,
        SUM(oi.quantity * oi.price_per_unit)                                    AS total_sales_value
    FROM orders o
    JOIN seller      se ON se.seller_id = o.seller_id
    JOIN order_items oi ON oi.order_id  = o.order_id
    GROUP BY o.seller_id, se.seller_name
)
SELECT
    seller_id,
    seller_name,
    total_orders,
    successful_orders,
    failed_orders,
    total_sales_value,
    ROUND(successful_orders * 100.0 / total_orders, 2) AS pct_successful_orders
FROM seller_sales
ORDER BY total_sales_value DESC
LIMIT 5;
 
 
/*
12. Product Profit Margin
Calculate the profit margin for each product (difference between price and cost of goods sold).
Challenge: Rank products by their profit margin, showing highest to lowest.
*/
SELECT
    product_id,
    product_name,
    price,
    cogs,
    (price - cogs)                                   AS profit_margin,
    ROUND((price - cogs) * 100.0 / price, 2)         AS profit_margin_pct,
    RANK() OVER (ORDER BY (price - cogs) DESC)       AS margin_rank
FROM product
ORDER BY profit_margin DESC;
 
 
/*
13. Most Returned Products
Query the top 10 products by the number of returns.
Challenge: Display the return rate as a percentage of total units sold for each product.
*/
WITH product_returns AS (
    SELECT
        oi.product_id,
        SUM(oi.quantity)                                                          AS total_units_sold,
        SUM(CASE WHEN s.delivery_status = 'Returned' THEN oi.quantity ELSE 0 END) AS total_units_returned
    FROM order_items oi
    JOIN shipping s ON s.order_id = oi.order_id
    GROUP BY oi.product_id
)
SELECT
    pr.product_id,
    p.product_name,
    pr.total_units_returned,
    pr.total_units_sold,
    ROUND(pr.total_units_returned * 100.0 / pr.total_units_sold, 2) AS return_rate_pct
FROM product_returns pr
JOIN product p ON p.product_id = pr.product_id
WHERE pr.total_units_returned > 0
ORDER BY pr.total_units_returned DESC
LIMIT 10;
 
 
/*
14. Orders Pending Shipment
Find orders that have been paid but are still pending shipment.
Challenge: Include order details, payment date, and customer information.
*/
SELECT
    o.order_id,
    CONCAT(cu.first_name, ' ', cu.last_name) AS customer_name,
    cu.state,
    o.order_date,
    pay.payment_date,
    pay.payment_status,
    s.delivery_status
FROM orders o
JOIN customer cu  ON cu.customer_id = o.customer_id
JOIN payments pay ON pay.order_id   = o.order_id
JOIN shipping s   ON s.order_id     = o.order_id
WHERE pay.payment_status = 'Completed'
  AND s.delivery_status  = 'Pending';
 
 
/*
15. Inactive Sellers
Identify sellers who haven't made any sales in the last 6 months.
Challenge: Show the last sale date and total sales from those sellers.
*/
WITH last_sale AS (
    SELECT seller_id, MAX(order_date) AS last_sale_date
    FROM orders
    GROUP BY seller_id
)
SELECT
    se.seller_id,
    se.seller_name,
    ls.last_sale_date,
    COALESCE(SUM(oi.quantity * oi.price_per_unit), 0) AS total_sales
FROM seller se
JOIN last_sale ls  ON ls.seller_id = se.seller_id
LEFT JOIN orders o      ON o.seller_id  = se.seller_id
LEFT JOIN order_items oi ON oi.order_id = o.order_id
WHERE ls.last_sale_date < (
    SELECT DATE_SUB(MAX(order_date), INTERVAL 6 MONTH) FROM orders
)
GROUP BY se.seller_id, se.seller_name, ls.last_sale_date
ORDER BY ls.last_sale_date;
 
 
/*
16. IDENTITY customers into returning or new
If the customer has done more than 5 returns categorize them as returning, otherwise new.
Challenge: List customer id, name, total orders, total returns.
*/
WITH customer_orders AS (
    SELECT
        o.customer_id,
        COUNT(DISTINCT o.order_id)                                     AS total_orders,
        SUM(CASE WHEN s.delivery_status = 'Returned' THEN 1 ELSE 0 END) AS total_returns
    FROM orders o
    JOIN shipping s ON s.order_id = o.order_id
    GROUP BY o.customer_id
)
SELECT
    co.customer_id,
    CONCAT(cu.first_name, ' ', cu.last_name) AS customer_name,
    co.total_orders,
    co.total_returns,
    CASE WHEN co.total_returns > 5 THEN 'Returning' ELSE 'New' END AS customer_type
FROM customer_orders co
JOIN customer cu ON cu.customer_id = co.customer_id
ORDER BY co.total_returns DESC;
 
 
/*
17. Cross-Sell Opportunities
Find customers who purchased product A but not product B
(e.g., customers who bought AirPods but not AirPods Max).
Challenge: Suggest cross-sell opportunities by displaying matching product categories.
*/
-- (a) Direct A-but-not-B check: replace the two product_id values as needed
SELECT DISTINCT o.customer_id
FROM orders o
JOIN order_items oi ON oi.order_id = o.order_id
WHERE oi.product_id = 101              -- product A
  AND o.customer_id NOT IN (
        SELECT o2.customer_id
        FROM orders o2
        JOIN order_items oi2 ON oi2.order_id = o2.order_id
        WHERE oi2.product_id = 102     -- product B
  );
 
-- (b) General-purpose version: customers who bought only ONE product within
-- a category are candidates to be cross-sold other products in that same category
SELECT
    o.customer_id,
    cat.category_id,
    cat.category_name,
    COUNT(DISTINCT oi.product_id) AS distinct_products_bought_in_category
FROM orders o
JOIN order_items oi ON oi.order_id  = o.order_id
JOIN product     p  ON p.product_id = oi.product_id
JOIN category    cat ON cat.category_id = p.category_id
GROUP BY o.customer_id, cat.category_id, cat.category_name
HAVING COUNT(DISTINCT oi.product_id) = 1
ORDER BY o.customer_id;
 
 
/*
18. Top 5 Customers by Orders in Each State
Identify the top 5 customers with the highest number of orders for each state.
Challenge: Include the number of orders and total sales for each customer.
*/
WITH customer_state_orders AS (
    SELECT
        cu.state,
        o.customer_id,
        CONCAT(cu.first_name, ' ', cu.last_name) AS customer_name,
        COUNT(DISTINCT o.order_id)                AS total_orders,
        SUM(oi.quantity * oi.price_per_unit)      AS total_sales,
        RANK() OVER (
            PARTITION BY cu.state
            ORDER BY COUNT(DISTINCT o.order_id) DESC
        ) AS rnk
    FROM orders o
    JOIN customer    cu ON cu.customer_id = o.customer_id
    JOIN order_items oi ON oi.order_id    = o.order_id
    GROUP BY cu.state, o.customer_id, cu.first_name, cu.last_name
)
SELECT state, customer_id, customer_name, total_orders, total_sales
FROM customer_state_orders
WHERE rnk <= 5
ORDER BY state, total_orders DESC;
 
 
/*
19. Revenue by Shipping Provider
Calculate the total revenue handled by each shipping provider.
Challenge: Include the total number of orders handled and the average
delivery time for each provider.
*/
SELECT
    s.shipping_providers,
    COUNT(DISTINCT s.order_id)                                    AS total_orders_handled,
    SUM(oi.quantity * oi.price_per_unit)                          AS total_revenue,
    ROUND(AVG(DATEDIFF(s.shipping_date, o.order_date)), 2)        AS avg_delivery_time_days
FROM shipping s
JOIN orders      o  ON o.order_id  = s.order_id
JOIN order_items oi ON oi.order_id = o.order_id
GROUP BY s.shipping_providers
ORDER BY total_revenue DESC;
 
 
/*
20. Top 10 product with highest decreasing revenue ratio compare to last
year (2022) and current_year (2023).
Challenge: Return product_id, product_name, category_name, 2022 revenue and
2023 revenue, decrease ratio at end. Round the ratio.
Note: Decrease ratio = (cr-ls)/ls * 100 (cr = current_year, ls = last_year)
*/
WITH yearly_revenue AS (
    SELECT
        oi.product_id,
        SUM(CASE WHEN YEAR(o.order_date) = 2022 THEN oi.quantity * oi.price_per_unit ELSE 0 END) AS revenue_2022,
        SUM(CASE WHEN YEAR(o.order_date) = 2023 THEN oi.quantity * oi.price_per_unit ELSE 0 END) AS revenue_2023
    FROM orders o
    JOIN order_items oi ON oi.order_id = o.order_id
    GROUP BY oi.product_id
)
SELECT
    yr.product_id,
    p.product_name,
    cat.category_name,
    yr.revenue_2022,
    yr.revenue_2023,
    ROUND(
        (yr.revenue_2023 - yr.revenue_2022) * 100.0 / NULLIF(yr.revenue_2022, 0), 2
    ) AS decrease_ratio_pct
FROM yearly_revenue yr
JOIN product  p   ON p.product_id   = yr.product_id
JOIN category cat ON cat.category_id = p.category_id
WHERE yr.revenue_2022 > 0
ORDER BY decrease_ratio_pct ASC
LIMIT 10;



